SET DEFINE OFF;
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    BRANCH_ID)
 Values
   (100, 'KHALED_KHORSID', 'M', 3020000, 'CEO', 
    1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (101, 'UBAIDULLAH', 'M', 2045000, 'CEO', 
    100, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (102, 'IJAZ_AHMED', 'M', 1535000, 'MANAGER', 
    101, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (103, 'MUHAMMAD_ARSLAN', 'M', 1055000, 'SENIOR', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (104, 'ALI_RAZA', 'M', 1015000, 'SENIOR', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (105, 'MIRNA_SAHYOUNI', 'F', 510000, 'SPECIALIST', 
    100, 1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (106, 'MUHAMMAD_IBRAHEM', 'M', 510000, 'ANALYST', 
    100, 1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (107, 'HAZEM_MUSA', 'M', 810000, 'DEVELOPER', 
    100, 1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (108, 'MAHMOUD_GAD', 'M', 810000, 'ENGINEER', 
    100, 1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (109, 'REHAN_ZAHID', 'M', 1515000, 'MANAGER', 
    101, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (110, 'HUMA_RIAZ', 'F', 815000, 'ENGINEER', 
    101, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (111, 'HASSAN_AHMED', 'M', 1015000, 'HR_MANAGER', 
    101, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (112, 'FATMA_YOUNES', 'F', 910000, 'QA_OFFICER', 
    100, 1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (113, 'AMR_ALI', 'M', 810000, 'ENGINEER', 
    100, 1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (114, 'MOSTAFA_BELAL', 'M', 910000, 'DEVELOPER', 
    100, 1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (115, 'MAIDA_TARIQ', 'F', 815000, 'DEVELOPER', 
    101, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (116, 'TALHA_TAHIR', 'M', 215000, 'ASSOCIATE', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (117, 'SHAMRIZE_KHAN', 'M', 315000, 'ASSOCIATE', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (118, 'KHALID', 'M', 319000, 'OFFICE_BOY', 
    101, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (119, 'RAMI_GHARIB', 'M', 1010000, 'MANAGER', 
    100, 1);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (120, 'RIZWAN_ALI', 'M', 625000, 'ENGINEER', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (121, 'JK', 'M', 715000, 'DEVELOPER', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (122, 'IBAD', 'M', 215000, 'ASSOCIATE', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (123, 'Faizan_Ahmed', 'M', 165000, 'JUNIOR', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (124, 'THOR', 'M', 150000, 'GUARD', 
    102, 2);
Insert into SHAMRIZEKHAN.EMPLOYEES
   (EMP_ID, EMP_NAME, GENDER, SALARY, DESIGNATION, 
    SUPERVISOR_ID, BRANCH_ID)
 Values
   (125, 'CAPTAIN_AMERICA', 'M', 150000, 'GUARD', 
    102, 2);
COMMIT;
